### ISSUE TITLE
Not muting on Pop!_OS 21.04

### ISSUE THREAD

**Issue by lvadla** [alexandrvicente/talkie#2]
Love this software!

I recently started using it on ubuntu (popos/gnome) and I am having the following problem:

`amixer: Unable to find simple control 'Capture',0`

The system tray icon indicates the default mute state and also indicates whenever I press the hotkey. However, it does not actually mute the microphone. Any idea how to resolve this?

Pop!_OS 21.04
GNOME 3.38.5

**Comment by alexandrvicente** [comment]
Thanks! This project does need some work to handle anything beyond a Capture mixer with a single audio card on Linux.

Could you provide the output of `amixer`?

**Comment by lvadla** [comment]
```$ arecord -l```
```
**** List of CAPTURE Hardware Devices ****
card 1: BRIO [Logitech BRIO], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: Microphone [Samson Q2U Microphone], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 4: PCH [HDA Intel PCH], device 0: ALC892 Analog [ALC892 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 4: PCH [HDA Intel PCH], device 2: ALC892 Alt Analog [ALC892 Alt Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
but `amixer` comes back empty

**Comment by lvadla** [comment]
Ok this is starting to make some sense. I think I received `Unable to find simple control 'Capture'` because audio speakers are the first card:

```amixer -c 0 info```
```
  Card hw:0 'Listen'/'Corsair Simple Audio Listen at usb-0000:00:14.0-3.1, full speed'
  Mixer name	: 'USB Mixer'
  Components	: 'USB1b1c:0a07'
  Controls      : 1
  Simple ctrls  : 0
```
```amixer -c 1 info```
```
  Card hw:1 'BRIO'/'Logitech BRIO at usb-0000:00:14.0-3.2, super speed'
  Mixer name	: 'USB Mixer'
  Components	: 'USB046d:085e'
  Controls      : 3
  Simple ctrls  : 1
```
```amixer -c 2 info```
```
   Card hw:2 'Microphone'/'Samson Technologies Samson Q2U Microphone at usb-0000:00:14.0-3.3, full speed'
  Mixer name	: 'USB Mixer'
  Components	: 'USB17a0:0304'
  Controls      : 7
  Simple ctrls  : 2
```

**Comment by lvadla** [comment]
I guess I could change "Capture" to "Mic" in `system("amixer set Capture nocap > /dev/null");` and then recompile the app, but out of curiosity, do you know a way to "alias" a simple mixer control to another name?

**Comment by alexandrvicente** [comment]
I'm not aware of any way to do that 😕
